locals {
  tags = merge(var.tags, {
    data_classification = var.data_classification
    data_residency      = "eu"
  })

  enhanced_monitoring = var.monitoring_interval_seconds > 0
}

data "aws_iam_policy_document" "monitoring_trust" {
  count = local.enhanced_monitoring ? 1 : 0

  statement {
    effect  = "Allow"
    actions = ["sts:AssumeRole"]

    principals {
      type        = "Service"
      identifiers = ["monitoring.rds.amazonaws.com"]
    }
  }
}

resource "aws_iam_role" "monitoring" {
  count = local.enhanced_monitoring ? 1 : 0

  name_prefix        = "${substr(var.identifier, 0, 24)}-mon-"
  description        = "RDS Enhanced Monitoring role for ${var.identifier}."
  assume_role_policy = data.aws_iam_policy_document.monitoring_trust[0].json

  tags = local.tags
}

resource "aws_iam_role_policy_attachment" "monitoring" {
  count = local.enhanced_monitoring ? 1 : 0

  role       = aws_iam_role.monitoring[0].name
  policy_arn = "arn:aws:iam::aws:policy/service-role/AmazonRDSEnhancedMonitoringRole"
}

resource "aws_db_subnet_group" "this" {
  name       = var.identifier
  subnet_ids = var.subnet_ids

  tags = local.tags
}

resource "aws_db_parameter_group" "this" {
  name_prefix = "${var.identifier}-"
  family      = var.parameter_group_family
  description = "TerraSov hardened parameters for ${var.identifier} (TLS enforced)."

  parameter {
    name  = "rds.force_ssl"
    value = "1"
  }

  tags = local.tags

  lifecycle {
    create_before_destroy = true
  }
}

resource "aws_db_instance" "this" {
  # checkov:skip=CKV_AWS_354:Performance Insights is optional (cost); when enabled it uses the CMK (performance_insights_kms_key_id).
  # checkov:skip=CKV_AWS_353:Same as CKV_AWS_354 - optional via enable_performance_insights.
  identifier = var.identifier

  engine         = "postgres"
  engine_version = var.engine_version
  instance_class = var.instance_class

  db_name  = var.db_name
  username = var.master_username

  # Master password is generated by RDS and stored in Secrets Manager encrypted
  # with the CMK - it never appears in variables, state or CI logs.
  manage_master_user_password   = true
  master_user_secret_kms_key_id = var.kms_key_arn

  iam_database_authentication_enabled = true

  storage_type          = "gp3"
  allocated_storage     = var.allocated_storage
  max_allocated_storage = var.max_allocated_storage > 0 ? var.max_allocated_storage : null
  storage_encrypted     = true
  kms_key_id            = var.kms_key_arn

  db_subnet_group_name   = aws_db_subnet_group.this.name
  vpc_security_group_ids = var.vpc_security_group_ids
  publicly_accessible    = false
  parameter_group_name   = aws_db_parameter_group.this.name

  multi_az            = var.multi_az
  deletion_protection = var.deletion_protection

  backup_retention_period   = var.backup_retention_days
  delete_automated_backups  = false
  copy_tags_to_snapshot     = true
  skip_final_snapshot       = false
  final_snapshot_identifier = "${var.identifier}-final"

  auto_minor_version_upgrade = true
  apply_immediately          = false

  enabled_cloudwatch_logs_exports = ["postgresql", "upgrade"]

  performance_insights_enabled          = var.enable_performance_insights
  performance_insights_kms_key_id       = var.enable_performance_insights ? var.kms_key_arn : null
  performance_insights_retention_period = var.enable_performance_insights ? 7 : null

  monitoring_interval = var.monitoring_interval_seconds
  monitoring_role_arn = local.enhanced_monitoring ? aws_iam_role.monitoring[0].arn : null

  tags = local.tags
}
